apiVersion: v2
name: argo-applications
description: A Helm chart for Kubernetes argo applications
type: application

version: 0.1.1

keywords:
  - argocd
  - workflows

maintainers:
  - name: juri
    url: https://github.com/juriku/helm-charts

dependencies:
  - name: base
    repository: file://../base
